FROM node:20-alpine AS base
WORKDIR /app

COPY package*.json ./
RUN npm install

# Copy sources code
COPY . .

#------------------------------------------------
# Development stage (Vite)
#------------------------------------------------
FROM base AS dev
ENV NODE_ENV=development
EXPOSE 5173

# Run Vite dev
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

#------------------------------------------------
# Build stage
#------------------------------------------------
FROM base AS build
ENV NODE_ENV=production

# Build Vue app
RUN npm run build

#------------------------------------------------
# Production stage (nginx)
#------------------------------------------------
FROM nginx:stable-alpine AS production

RUN rm -rf /usr/share/nginx/html/*

# Copy from build stage to nginx
COPY --from=build /app/dist /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"]