FROM node:20-alpine AS deps
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

#-----------------------------
# Development stage
#-----------------------------
FROM node:20-alpine AS dev

ENV NODE_ENV=development

COPY --from=deps /app/node_modules ./node_modules
COPY . .

EXPOSE 3000

# Run the development server
CMD ["npm", "run", "serve"]

#-----------------------------
# Build stage
#-----------------------------
FROM node:20-alpine AS build
WORKDIR /app
ENV NODE_ENV=production

COPY package*.json ./
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Build TypeScript to JavaScript
RUN npm run build

#-----------------------------
# Production stage
#-----------------------------
FROM node:20-alpine AS production
WORKDIR /app

ENV NODE_ENV=production

# Copy package.json and package-lock.json
COPY package*.json ./

# Install only production dependencies
RUN npm install --production

# Copy built JS from build stage
COPY --from=build /app/dist ./dist
COPY --from=build /app/prisma ./prisma

EXPOSE 3000

CMD ["sh","-c", "npx prisma generate && node dist/server.js"]
