ARG MODE=production
FROM node:latest AS base

WORKDIR /app

#Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

#Copy the rest of the application code
COPY . .

# Copy prisma schema
COPY prisma ./prisma

#------------------------------------------------
# Development stage
#------------------------------------------------
FROM base AS dev
ENV NODE_ENV=development
EXPOSE 3000
# Start the application in development mode
CMD ["npm", "start"]

#------------------------------------------------
# Production stage
#------------------------------------------------
FROM base AS production
ENV NODE_ENV=production

# Generate Prisma Client
RUN npx prisma generate

# Build TypeScript
RUN npm run build

# Remove dev dependencies
RUN npm prune --production
EXPOSE 3000
CMD ["npm", "run", "serve"]

#------------------------------------------------
# Final stage
#------------------------------------------------
FROM ${MODE} AS final