FROM node:20-alpine AS deps
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

#-----------------------------
# Development stage
#-----------------------------
FROM deps AS dev

ENV NODE_ENV=development

COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN npm prisma generate
RUN npm run builds

EXPOSE 3000

# Run the development server
CMD ["npm", "run", "serve"]

#-----------------------------
# Build stage
#-----------------------------
FROM deps AS build
WORKDIR /app
ENV NODE_ENV=production

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Generate Prisma client
RUN npx prisma generate

# Build TypeScript to JavaScript
RUN npm run build

#-----------------------------
# Production stage
#-----------------------------
FROM deps AS production
WORKDIR /app

ENV NODE_ENV=production

# Install only production dependencies
RUN npm install --production

# Copy built JS from build stage
COPY --from=build /app/dist ./dist
COPY --from=build /app/prisma ./prisma

COPY package*.json ./

EXPOSE 3000

CMD ["sh", "-c", "while true; do sleep 1000; done"]

